site_name: Cyber Defence Kit

nav:
  - Home: index.md
  - Cyber Defence Kit:
      - 'Cyber Defence Kit Explained': Cyber Defence Kit Explained/Cyber Defence Kit Explained.md
      - 'Project Overview': Project Overview/Project Overview.md

theme:
  name: material
  logo: images/Cyber Defence Kit logo.png
  favicon: images/Cyber Defence Kit logo.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: light blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: light blue
plugins:
  - social
  - search
  - glightbox
  - offline

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cyberdefencekit

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - md_in_html
  - tables
  - toc:
      title: On this page
  
copyright: |
  &copy; 2024 <a href="https://github.com/cyberdefencekit"  target="_blank" rel="noopener">Cyber Defence Kit - Joseph Jee</a>
